services:
  openalgo:
    image: openalgo:latest
    build:
      context: .
      dockerfile: Dockerfile

    container_name: openalgo-web
    ports:
      - "${FLASK_PORT:-5000}:5000"
      - "${WEBSOCKET_PORT:-8765}:8765"

    # persistent DB, logs + mount the host .env read-only so dotenv can read it
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - ./.env:/app/.env:ro   # ← .env stays on your machine

    # (optional) extra env-vars that are NOT in .env
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}

    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openalgo
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: aa123456
    ports:
      - "3307:3306"
    volumes:
      - mariadb_volume:/var/lib/mysql
      - ./mariadb/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mariadb_volume:
